// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v5.29.3
// source: service/module/delivery/grpc/model/tracking.proto

package protocol_buffer

import (
	grpc "google.golang.org/grpc"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// PersonalFinancialTrackingServiceClient is the client API for PersonalFinancialTrackingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PersonalFinancialTrackingServiceClient interface {
}

type personalFinancialTrackingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPersonalFinancialTrackingServiceClient(cc grpc.ClientConnInterface) PersonalFinancialTrackingServiceClient {
	return &personalFinancialTrackingServiceClient{cc}
}

// PersonalFinancialTrackingServiceServer is the server API for PersonalFinancialTrackingService service.
// All implementations must embed UnimplementedPersonalFinancialTrackingServiceServer
// for forward compatibility
type PersonalFinancialTrackingServiceServer interface {
	mustEmbedUnimplementedPersonalFinancialTrackingServiceServer()
}

// UnimplementedPersonalFinancialTrackingServiceServer must be embedded to have forward compatible implementations.
type UnimplementedPersonalFinancialTrackingServiceServer struct {
}

func (UnimplementedPersonalFinancialTrackingServiceServer) mustEmbedUnimplementedPersonalFinancialTrackingServiceServer() {
}

// UnsafePersonalFinancialTrackingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PersonalFinancialTrackingServiceServer will
// result in compilation errors.
type UnsafePersonalFinancialTrackingServiceServer interface {
	mustEmbedUnimplementedPersonalFinancialTrackingServiceServer()
}

func RegisterPersonalFinancialTrackingServiceServer(s grpc.ServiceRegistrar, srv PersonalFinancialTrackingServiceServer) {
	s.RegisterService(&PersonalFinancialTrackingService_ServiceDesc, srv)
}

// PersonalFinancialTrackingService_ServiceDesc is the grpc.ServiceDesc for PersonalFinancialTrackingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PersonalFinancialTrackingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "personal_financial_tracking.PersonalFinancialTrackingService",
	HandlerType: (*PersonalFinancialTrackingServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams:     []grpc.StreamDesc{},
	Metadata:    "service/module/delivery/grpc/model/tracking.proto",
}
